sudo: required
  
language: python

python:
    - 2.7

addons:
    apt:
        packages:
            - build-essential
            - curl
            - git
            - pkg-config
            - software-properties-common
            - python-dev
            - python3-dev
            - libfftw3-dev
            - libgdbm-dev

script:
    - sudo pip --no-cache-dir install \
        setuptools \
        numpy \
        matplotlib \
        scipy \
        pylint \
        coveralls \
        codecov
    - sudo pip --no-cache-dir install \
        aipy \
        pyephem \
        lsl
    - python setup.py build
    - python setup.py test

after_success:
    - cd tests
    - coveralls
    - codecov
